version: '3.7'

services:
    db:
        image: postgres:10.1-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        command: python /mikou_test/manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/mikou_test
        ports:
          - 8000:8000
        depends_on:
          - db
        links:
          - postgres:postgres
          - redis:redis
    redis:
        container_name: 'redis'
        image: 'redis:3.2.0'
        ports:
          - '127.0.0.1:6379:6379'
        volumes:
          - 'redisdata:/data'
